{"name": "test_login_invalid_credentials", "status": "passed", "description": "Test login with invalid credentials.", "start": 1738257191983, "stop": 1738257192196, "uuid": "3386f33e-7d15-426b-b5d2-83586770a0bb", "historyId": "9b4b57c5799fe6899f9dbc4d91980667", "testCaseId": "9b4b57c5799fe6899f9dbc4d91980667", "fullName": "tests.test_auth#test_login_invalid_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth"}, {"name": "host", "value": "Ivan"}, {"name": "thread", "value": "1680-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth"}]}